name: Generate IWD Archive

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in src
        id: check_changes
        run: |
          git fetch origin master
          if git diff --quiet origin/master -- ./src; then
            echo "No changes in ./src, skipping release."
            exit 78
          fi
          echo "Changes detected in ./src, proceeding with release."

      - name: Get latest version tag
        id: get_version
        run: |
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1 || echo "v0.0.0")
          IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
          major=${version_parts[0]:-0}
          minor=${version_parts[1]:-0}
          patch=${version_parts[2]:-0}
          
          commit_messages=$(git log --format=%s -1)
          
          if echo "$commit_messages" | grep -qE "^feat"; then
            major=$((major + 1))
            minor=0
            patch=0
          elif echo "$commit_messages" | grep -qE "^fix"; then
            patch=$((patch + 1))
          else
            minor=$((minor + 1))
            patch=0
          fi
          
          new_version="v${major}.${minor}.${patch}"
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "Generated version: $new_version"

      - name: Delete existing tag if exists
        run: |
          if git rev-parse ${{ env.new_version }} >/dev/null 2>&1; then
            git tag -d ${{ env.new_version }}
            git push --delete origin ${{ env.new_version }}
          fi

      - name: Create new tag
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}

      - name: Create IWD archive
        run: |
          mkdir -p build
          zip -r build/zzz_LocalJumpMod.iwd ./src -x "*.git*" "build/*"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_version }}
          release_name: IWD Release ${{ env.new_version }}
          draft: false
          prerelease: false

      - name: Upload IWD archive to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/zzz_LocalJumpMod.iwd
          asset_name: zzz_LocalJumpMod.iwd
          asset_content_type: application/zip
